# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub }:

final: prev:
{
  alpha-nvim = buildVimPluginFrom2Nix {
    pname = "alpha-nvim";
    version = "2022-01-18";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "46471d6720fc1910556151dacffc706fa9f434e6";
      sha256 = "03s2mi0n8haijd7vpiqvilzwlxi2lggd9x0d9a8cybvn80lkk5sn";
    };
    meta.homepage = "https://github.com/goolord/alpha-nvim/";
  };

  cmp-buffer = buildVimPluginFrom2Nix {
    pname = "cmp-buffer";
    version = "2022-01-04";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "f83773e2f433a923997c5faad7ea689ec24d1785";
      sha256 = "0z1c0x60hz3khgpp7nfj0i579sgi4vsnhhcqb02i7a8jx685qwrd";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-buffer/";
  };

  cmp-calc = buildVimPluginFrom2Nix {
    pname = "cmp-calc";
    version = "2021-10-11";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-calc";
      rev = "eb7bd1d7382ac26d8eb7346e36405c0ae94333a2";
      sha256 = "0b88fn4zb2sp4c9fnn9m8qb41djv17mmydhx6bryqnrc8mqycajy";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-calc/";
  };

  cmp-cmdline = buildVimPluginFrom2Nix {
    pname = "cmp-cmdline";
    version = "2021-12-01";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "29ca81a6f0f288e6311b3377d9d9684d22eac2ec";
      sha256 = "0yzh0jdys1bn1c2mqm410c0ndyyyxpmigzdrkhnkv78b16vjyhq6";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-cmdline/";
  };

  cmp-emoji = buildVimPluginFrom2Nix {
    pname = "cmp-emoji";
    version = "2021-09-28";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-emoji";
      rev = "19075c36d5820253d32e2478b6aaf3734aeaafa0";
      sha256 = "00jrwg491q6nx3q36krarxfpchg3fgdsz7l02ag7cm0x9hv4dknd";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-emoji/";
  };

  cmp-nvim-lsp = buildVimPluginFrom2Nix {
    pname = "cmp-nvim-lsp";
    version = "2022-01-15";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "ebdfc204afb87f15ce3d3d3f5df0b8181443b5ba";
      sha256 = "0kmaxxdxlp1s5w36khnw0sdrbv1lr3p5n9r90h6h7wv842n4mnca";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-nvim-lsp/";
  };

  cmp-nvim-lsp-document-symbol = buildVimPluginFrom2Nix {
    pname = "cmp-nvim-lsp-document-symbol";
    version = "2021-10-28";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp-document-symbol";
      rev = "29d12e55cf49ee07b829114ad39b161cad2544ab";
      sha256 = "0w4m34467j3cg4dj69r12115p5k1i2lbjzmwx5hmd5x6xzb5qycb";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-nvim-lsp-document-symbol/";
  };

  cmp-nvim-lua = buildVimPluginFrom2Nix {
    pname = "cmp-nvim-lua";
    version = "2021-10-11";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lua";
      rev = "d276254e7198ab7d00f117e88e223b4bd8c02d21";
      sha256 = "11mhpb2jdc7zq7yiwzkks844b7alrdd08h96r6y7p3cxjv1iy5gz";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-nvim-lua/";
  };

  cmp-omni = buildVimPluginFrom2Nix {
    pname = "cmp-omni";
    version = "2022-01-08";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-omni";
      rev = "7a457f0c4f9e0801fee777d955eb841659aa3b84";
      sha256 = "0f9mk0h3g1gg6lq9qnasi0liv8kvgc6rzfvgc9cflq5kkw97gjpw";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-omni/";
  };

  cmp-path = buildVimPluginFrom2Nix {
    pname = "cmp-path";
    version = "2022-01-17";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "c5230cb439df9547294678d0f1c1465ad7989e5f";
      sha256 = "0ya68crpc78fb5zn34s06rl77gsm956pjpsjfk1dv2cddwwxi8x8";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-path/";
  };

  cmp-vsnip = buildVimPluginFrom2Nix {
    pname = "cmp-vsnip";
    version = "2021-11-10";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-vsnip";
      rev = "0abfa1860f5e095a07c477da940cfcb0d273b700";
      sha256 = "1vhw2qx8284bskivc2jyijl93g1b1z9hzzbq2l9b4aw6r23frbgc";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-vsnip/";
  };

  cmp_luasnip = buildVimPluginFrom2Nix {
    pname = "cmp_luasnip";
    version = "2022-01-02";
    src = fetchFromGitHub {
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "d6f837f4e8fe48eeae288e638691b91b97d1737f";
      sha256 = "0cmfjqps7j3056y8avkrfz40kx8qcdxf4v1xvfv03nrw9xdwwh5y";
    };
    meta.homepage = "https://github.com/saadparwaiz1/cmp_luasnip/";
  };

  completion-treesitter = buildVimPluginFrom2Nix {
    pname = "completion-treesitter";
    version = "2020-06-26";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "completion-treesitter";
      rev = "45c9b2faff4785539a0d0c655440c2465fed985a";
      sha256 = "19pgdzzk7zq85b1grfjf0nncvs5vxrd4rj1p90iw2amq4mvqrx3l";
    };
    meta.homepage = "https://github.com/nvim-treesitter/completion-treesitter/";
  };

  firenvim = buildVimPluginFrom2Nix {
    pname = "firenvim";
    version = "2022-01-12";
    src = fetchFromGitHub {
      owner = "glacambre";
      repo = "firenvim";
      rev = "a52a325120d357cf767137114bdab37044c11acd";
      sha256 = "01gqr4x73vii88w90d2xd07f8zqa6z57qrzxxi36b2dzwz7lmghl";
    };
    meta.homepage = "https://github.com/glacambre/firenvim/";
  };

  lualine-nvim = buildVimPluginFrom2Nix {
    pname = "lualine.nvim";
    version = "2022-01-12";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "70691ae350fdbe1f15758e3b8e2973742a7967a9";
      sha256 = "02djs872iy9w675yrh2777d5rbb9maz26y8nfwdw9j2xm182xm6y";
    };
    meta.homepage = "https://github.com/nvim-lualine/lualine.nvim/";
  };

  luasnip = buildVimPluginFrom2Nix {
    pname = "luasnip";
    version = "2022-01-13";
    src = fetchFromGitHub {
      owner = "l3mon4d3";
      repo = "luasnip";
      rev = "0222ee63c9e4b80e6000d064f8efd8edcc6d0c48";
      sha256 = "1hjzzrxlq0h59mvd0ids62k5ps1invvawdj60q8my3arrlfbnb4v";
    };
    meta.homepage = "https://github.com/l3mon4d3/luasnip/";
  };

  neorg = buildVimPluginFrom2Nix {
    pname = "neorg";
    version = "2022-01-19";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg";
      rev = "24b6431034dfba5029c23680722d44f6623808f9";
      sha256 = "1kmk8dsbs06bb6if7272y009yrfr7kqfcsrrkbb25x2kk08s7jv7";
    };
    meta.homepage = "https://github.com/nvim-neorg/neorg/";
  };

  neovim-sensible = buildVimPluginFrom2Nix {
    pname = "neovim-sensible";
    version = "2017-09-20";
    src = fetchFromGitHub {
      owner = "jeffkreeftmeijer";
      repo = "neovim-sensible";
      rev = "e7ab7544f15e59de2d9a1b42f58e590938e496e7";
      sha256 = "06whnfvmzfdsx9gvkd2nxhx29939gjzibr2xadh54sj8ns646w58";
    };
    meta.homepage = "https://github.com/jeffkreeftmeijer/neovim-sensible/";
  };

  nightfox-nvim = buildVimPluginFrom2Nix {
    pname = "nightfox.nvim";
    version = "2022-01-06";
    src = fetchFromGitHub {
      owner = "EdenEast";
      repo = "nightfox.nvim";
      rev = "9c536aa95f80dd9f5eb08da8499fc5f6145407aa";
      sha256 = "1hcbzwyqr5zypl6v9q6b2c2y7zjvql84mc2ip07066090v6l3qx7";
    };
    meta.homepage = "https://github.com/EdenEast/nightfox.nvim/";
  };

  nvim-cmp = buildVimPluginFrom2Nix {
    pname = "nvim-cmp";
    version = "2022-01-18";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "8fc8d31cf451b8becb39087aa2190bee29a8b009";
      sha256 = "1z2yq2ssbny5hp5vxr61ap2y0nkfrwqh1ar50q2d1709xl6j4rzn";
    };
    meta.homepage = "https://github.com/hrsh7th/nvim-cmp/";
  };

  nvim-lspconfig = buildVimPluginFrom2Nix {
    pname = "nvim-lspconfig";
    version = "2022-01-18";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "37edd90592ef0e4b603634e449ce28b053d9bdd0";
      sha256 = "0zz7hbhgzrqsvahdbb643inmz3i3ag9cdlxz2qg6lxwwql2zzd3b";
    };
    meta.homepage = "https://github.com/neovim/nvim-lspconfig/";
  };

  nvim-treesitter = buildVimPluginFrom2Nix {
    pname = "nvim-treesitter";
    version = "2022-01-19";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "983c46d55cb796fd623d43e3510bce7b21d0d1a6";
      sha256 = "15aqlq9l03knpzzgjl6fjf7nh30azdgawwcl9ziq7nfighdyd4yp";
    };
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter/";
  };

  nvim-web-devicons = buildVimPluginFrom2Nix {
    pname = "nvim-web-devicons";
    version = "2022-01-18";
    src = fetchFromGitHub {
      owner = "kyazdani42";
      repo = "nvim-web-devicons";
      rev = "634e26818f2bea9161b7efa76735746838971824";
      sha256 = "1pfhaa7xx3r4nq9bz3zj8hb1qbh5rjhmlxn1f8l7ihvbhb0s0f6z";
    };
    meta.homepage = "https://github.com/kyazdani42/nvim-web-devicons/";
  };

  plenary-nvim = buildVimPluginFrom2Nix {
    pname = "plenary.nvim";
    version = "2022-01-05";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "563d9f6d083f0514548f2ac4ad1888326d0a1c66";
      sha256 = "1i4sj56fral52xa2wqzx331a6xza4ksi0n6092g6q93kxx202xwq";
    };
    meta.homepage = "https://github.com/nvim-lua/plenary.nvim/";
  };

  popup-nvim = buildVimPluginFrom2Nix {
    pname = "popup.nvim";
    version = "2021-11-18";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "popup.nvim";
      rev = "b7404d35d5d3548a82149238289fa71f7f6de4ac";
      sha256 = "093r3cy02gfp7sphrag59n3fjhns7xdsam1ngiwhwlig3bzv7mbl";
    };
    meta.homepage = "https://github.com/nvim-lua/popup.nvim/";
  };

  telescope-file-browser-nvim = buildVimPluginFrom2Nix {
    pname = "telescope-file-browser.nvim";
    version = "2022-01-18";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "dd101ff876de4cfcb498ae7e9cb9f942d5cd7f95";
      sha256 = "07bmkk6ylcpj808k7nl2igx7j8mypblv54vzhmx0aqbxjs4xswrx";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope-file-browser.nvim/";
  };

  telescope-fzf-native-nvim = buildVimPluginFrom2Nix {
    pname = "telescope-fzf-native.nvim";
    version = "2021-11-24";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-fzf-native.nvim";
      rev = "b8662b076175e75e6497c59f3e2799b879d7b954";
      sha256 = "0wj7ip9c17m4ij9sw5rq1bqy5hb367b32iz9b14pgg110cvfgpw1";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope-fzf-native.nvim/";
  };

  telescope-github-nvim = buildVimPluginFrom2Nix {
    pname = "telescope-github.nvim";
    version = "2022-01-18";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-github.nvim";
      rev = "abe424a49a5d3ba8532d4c245611874626795f24";
      sha256 = "1dyh2iiz2aqm43gwlm326n47bskm5g9skpb1l6s640x1zkhldimk";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope-github.nvim/";
  };

  telescope-nvim = buildVimPluginFrom2Nix {
    pname = "telescope.nvim";
    version = "2022-01-18";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "0011b1148d3975600f5a9f0be8058cdaac4e30d9";
      sha256 = "129cha5pwr1blnkyvkl59ildap0zdvk2khajmvd79fkcncgffvfi";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope.nvim/";
  };

  vim-sensible = buildVimPluginFrom2Nix {
    pname = "vim-sensible";
    version = "2019-11-24";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-sensible";
      rev = "2d9f34c09f548ed4df213389caa2882bfe56db58";
      sha256 = "153i3kh44ri046va3qdrbvvsv7gy25fsd9pc2yhrg23lvj169zfp";
    };
    meta.homepage = "https://github.com/tpope/vim-sensible/";
  };

  which-key-nvim = buildVimPluginFrom2Nix {
    pname = "which-key.nvim";
    version = "2022-01-19";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "28d2bd129575b5e9ebddd88506601290bb2bb221";
      sha256 = "13k1q7zkwr5bfc2lj97nk4npy0gk49r1qbac49aib7fyzirkagkg";
    };
    meta.homepage = "https://github.com/folke/which-key.nvim/";
  };

}
