# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "ejs-2.5.2" = {
      name = "ejs";
      packageName = "ejs";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ejs/-/ejs-2.5.2.tgz";
        sha1 = "21444ba09386f0c65b6eafb96a3d51bcb3be80d1";
      };
    };
    "fs-promise-0.3.1" = {
      name = "fs-promise";
      packageName = "fs-promise";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-promise/-/fs-promise-0.3.1.tgz";
        sha1 = "bf34050368f24d6dc9dfc6688ab5cead8f86842a";
      };
    };
    "js-yaml-3.6.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.6.1.tgz";
        sha1 = "6e5fe67d8b205ce4d22fad05b7781e8dadcc4b30";
      };
    };
    "limax-1.4.1" = {
      name = "limax";
      packageName = "limax";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/limax/-/limax-1.4.1.tgz";
        sha1 = "1c0c3132250bcd53ee64363f8019652da3eb9a95";
      };
    };
    "meow-3.7.0" = {
      name = "meow";
      packageName = "meow";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/meow/-/meow-3.7.0.tgz";
        sha1 = "72cb668b425228290abbfa856892587308a801fb";
      };
    };
    "open-0.0.5" = {
      name = "open";
      packageName = "open";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-0.0.5.tgz";
        sha1 = "42c3e18ec95466b6bf0dc42f3a2945c3f0cad8fc";
      };
    };
    "update-notifier-0.6.3" = {
      name = "update-notifier";
      packageName = "update-notifier";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-notifier/-/update-notifier-0.6.3.tgz";
        sha1 = "776dec8daa13e962a341e8a1d98354306b67ae08";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz";
        sha1 = "c5061b6e0ef8a81775e50f5d66151bf6bf371107";
      };
    };
    "any-promise-0.1.0" = {
      name = "any-promise";
      packageName = "any-promise";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/any-promise/-/any-promise-0.1.0.tgz";
        sha1 = "830b680aa7e56f33451d4b049f3bd8044498ee27";
      };
    };
    "argparse-1.0.9" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.9.tgz";
        sha1 = "73d83bc263f86e97f8cc4f6bae1b0e90a7d22c86";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "hepburn-1.0.0" = {
      name = "hepburn";
      packageName = "hepburn";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hepburn/-/hepburn-1.0.0.tgz";
        sha1 = "49ce862942a77570cd4f5c8fe100b85d942cb61b";
      };
    };
    "pinyin-2.6.2" = {
      name = "pinyin";
      packageName = "pinyin";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinyin/-/pinyin-2.6.2.tgz";
        sha1 = "2b7e46eeb5c9de5d6f7b6b86be7e0f15ff5d8c89";
      };
    };
    "speakingurl-10.0.0" = {
      name = "speakingurl";
      packageName = "speakingurl";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/speakingurl/-/speakingurl-10.0.0.tgz";
        sha1 = "24ef980de85194d17f2daea30a6b2c2cc51115bb";
      };
    };
    "bulk-replace-0.0.1" = {
      name = "bulk-replace";
      packageName = "bulk-replace";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bulk-replace/-/bulk-replace-0.0.1.tgz";
        sha1 = "f095682a896abd4b3d9e08de409cc222e213f9dd";
      };
    };
    "commander-1.1.1" = {
      name = "commander";
      packageName = "commander";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-1.1.1.tgz";
        sha1 = "50d1651868ae60eccff0a2d9f34595376bc6b041";
      };
    };
    "nodejieba-1.4.11" = {
      name = "nodejieba";
      packageName = "nodejieba";
      version = "1.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/nodejieba/-/nodejieba-1.4.11.tgz";
        sha1 = "888604861f378111494f81a83cd30965ce75eba7";
      };
    };
    "keypress-0.1.0" = {
      name = "keypress";
      packageName = "keypress";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz";
        sha1 = "4a3188d4291b66b4f65edb99f806aa9ae293592a";
      };
    };
    "nan-2.3.5" = {
      name = "nan";
      packageName = "nan";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.3.5.tgz";
        sha1 = "822a0dc266290ce4cd3a12282ca3e7e364668a08";
      };
    };
    "camelcase-keys-2.1.0" = {
      name = "camelcase-keys";
      packageName = "camelcase-keys";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase-keys/-/camelcase-keys-2.1.0.tgz";
        sha1 = "308beeaffdf28119051efa1d932213c91b8f92e7";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "loud-rejection-1.6.0" = {
      name = "loud-rejection";
      packageName = "loud-rejection";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loud-rejection/-/loud-rejection-1.6.0.tgz";
        sha1 = "5b46f80147edee578870f086d04821cf998e551f";
      };
    };
    "map-obj-1.0.1" = {
      name = "map-obj";
      packageName = "map-obj";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-obj/-/map-obj-1.0.1.tgz";
        sha1 = "d933ceb9205d82bdcf4886f6742bdc2b4dea146d";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "normalize-package-data-2.3.5" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.3.5.tgz";
        sha1 = "8d924f142960e1777e7ffe170543631cc7cb02df";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "read-pkg-up-1.0.1" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-1.0.1.tgz";
        sha1 = "9d63c13276c065918d57f002a57f40a1b643fb02";
      };
    };
    "redent-1.0.0" = {
      name = "redent";
      packageName = "redent";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redent/-/redent-1.0.0.tgz";
        sha1 = "cf916ab1fd5f1f16dfb20822dd6ec7f730c2afde";
      };
    };
    "trim-newlines-1.0.0" = {
      name = "trim-newlines";
      packageName = "trim-newlines";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-newlines/-/trim-newlines-1.0.0.tgz";
        sha1 = "5887966bb582a4503a41eb524f7d35011815a613";
      };
    };
    "camelcase-2.1.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-2.1.1.tgz";
        sha1 = "7c1d16d679a1bbe59ca02cacecfb011e201f5a1f";
      };
    };
    "currently-unhandled-0.4.1" = {
      name = "currently-unhandled";
      packageName = "currently-unhandled";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/currently-unhandled/-/currently-unhandled-0.4.1.tgz";
        sha1 = "988df33feab191ef799a61369dd76c17adf957ea";
      };
    };
    "signal-exit-3.0.1" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.1.tgz";
        sha1 = "5a4c884992b63a7acd9badb7894c3ee9cfccad81";
      };
    };
    "array-find-index-1.0.2" = {
      name = "array-find-index";
      packageName = "array-find-index";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-find-index/-/array-find-index-1.0.2.tgz";
        sha1 = "df010aa1287e164bbda6f9723b0a96a1ec4187a1";
      };
    };
    "hosted-git-info-2.1.5" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.1.5.tgz";
        sha1 = "0ba81d90da2e25ab34a332e6ec77936e1598118b";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "validate-npm-package-license-3.0.1" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.1.tgz";
        sha1 = "2804babe712ad3379459acfbe24746ab2c303fbc";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "spdx-correct-1.0.2" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-1.0.2.tgz";
        sha1 = "4b3073d933ff51f3912f03ac5519498a4150db40";
      };
    };
    "spdx-expression-parse-1.0.4" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-1.0.4.tgz";
        sha1 = "9bdf2f20e1f40ed447fbe273266191fced51626c";
      };
    };
    "spdx-license-ids-1.2.2" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-1.2.2.tgz";
        sha1 = "c9df7a3424594ade6bd11900d596696dc06bac57";
      };
    };
    "find-up-1.1.2" = {
      name = "find-up";
      packageName = "find-up";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-1.1.2.tgz";
        sha1 = "6b2e9822b1a2ce0a60ab64d610eccad53cb24d0f";
      };
    };
    "read-pkg-1.1.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-1.1.0.tgz";
        sha1 = "f5ffaa5ecd29cb31c0474bca7d756b6bb29e3f28";
      };
    };
    "path-exists-2.1.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-2.1.0.tgz";
        sha1 = "0feb6c64f0fc518d9a754dd5efb62c7022761f4b";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "load-json-file-1.1.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-1.1.0.tgz";
        sha1 = "956905708d58b4bab4c2261b04f59f31c99374c0";
      };
    };
    "path-type-1.1.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-1.1.0.tgz";
        sha1 = "59c44f7ee491da704da415da5a4070ba4f8fe441";
      };
    };
    "graceful-fs-4.1.9" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.9.tgz";
        sha1 = "baacba37d19d11f9d146d3578bc99958c3787e29";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "strip-bom-2.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz";
        sha1 = "6219a85616520491f35788bdbf1447a99c7e6b0e";
      };
    };
    "error-ex-1.3.0" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.0.tgz";
        sha1 = "e67b43f3e82c96ea3a584ffee0b9fc3325d802d9";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-utf8-0.2.1" = {
      name = "is-utf8";
      packageName = "is-utf8";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-utf8/-/is-utf8-0.2.1.tgz";
        sha1 = "4b0da1442104d1b336340e80797e865cf39f7d72";
      };
    };
    "indent-string-2.1.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-2.1.0.tgz";
        sha1 = "8e2d48348742121b4a8218b7a137e9a52049dc80";
      };
    };
    "strip-indent-1.0.1" = {
      name = "strip-indent";
      packageName = "strip-indent";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-indent/-/strip-indent-1.0.1.tgz";
        sha1 = "0c7962a6adefa7bbd4ac366460a638552ae1a0a2";
      };
    };
    "repeating-2.0.1" = {
      name = "repeating";
      packageName = "repeating";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeating/-/repeating-2.0.1.tgz";
        sha1 = "5214c53a926d3552707527fbab415dbc08d06dda";
      };
    };
    "is-finite-1.0.2" = {
      name = "is-finite";
      packageName = "is-finite";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-finite/-/is-finite-1.0.2.tgz";
        sha1 = "cc6677695602be550ef11e8b4aa6305342b6d0aa";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "get-stdin-4.0.1" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-4.0.1.tgz";
        sha1 = "b968c6b0a04384324902e8bf1a5df32579a450fe";
      };
    };
    "boxen-0.3.1" = {
      name = "boxen";
      packageName = "boxen";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boxen/-/boxen-0.3.1.tgz";
        sha1 = "a7d898243ae622f7abb6bb604d740a76c6a5461b";
      };
    };
    "configstore-2.1.0" = {
      name = "configstore";
      packageName = "configstore";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-2.1.0.tgz";
        sha1 = "737a3a7036e9886102aa6099e47bb33ab1aba1a1";
      };
    };
    "is-npm-1.0.0" = {
      name = "is-npm";
      packageName = "is-npm";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-npm/-/is-npm-1.0.0.tgz";
        sha1 = "f2fb63a65e4905b406c86072765a1a4dc793b9f4";
      };
    };
    "latest-version-2.0.0" = {
      name = "latest-version";
      packageName = "latest-version";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/latest-version/-/latest-version-2.0.0.tgz";
        sha1 = "56f8d6139620847b8017f8f1f4d78e211324168b";
      };
    };
    "semver-diff-2.1.0" = {
      name = "semver-diff";
      packageName = "semver-diff";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-diff/-/semver-diff-2.1.0.tgz";
        sha1 = "4bbb8437c8d37e4b0cf1a68fd726ec6d645d6d36";
      };
    };
    "filled-array-1.1.0" = {
      name = "filled-array";
      packageName = "filled-array";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filled-array/-/filled-array-1.1.0.tgz";
        sha1 = "c3c4f6c663b923459a9aa29912d2d031f1507f84";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "widest-line-1.0.0" = {
      name = "widest-line";
      packageName = "widest-line";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/widest-line/-/widest-line-1.0.0.tgz";
        sha1 = "0c09c85c2a94683d0d7eaf8ee097d564bf0e105c";
      };
    };
    "code-point-at-1.0.1" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.0.1.tgz";
        sha1 = "1104cd34f9b5b45d3eba88f1babc1924e1ce35fb";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "dot-prop-3.0.0" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-3.0.0.tgz";
        sha1 = "1b708af094a49c9a0e7dbcad790aba539dac1177";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "osenv-0.1.3" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.3.tgz";
        sha1 = "83cf05c6d6458fc4d5ac6362ea325d92f2754217";
      };
    };
    "uuid-2.0.3" = {
      name = "uuid";
      packageName = "uuid";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-2.0.3.tgz";
        sha1 = "67e2e863797215530dff318e5bf9dcebfd47b21a";
      };
    };
    "write-file-atomic-1.2.0" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.2.0.tgz";
        sha1 = "14c66d4e4cb3ca0565c28cf3b7a6f3e4d5938fab";
      };
    };
    "xdg-basedir-2.0.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-2.0.0.tgz";
        sha1 = "edbc903cc385fc04523d966a335504b5504d1bd2";
      };
    };
    "is-obj-1.0.1" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-1.0.1.tgz";
        sha1 = "3e4729ac1f5fde025cd7d83a896dab9f4f67db0f";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "slide-1.1.6" = {
      name = "slide";
      packageName = "slide";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/slide/-/slide-1.1.6.tgz";
        sha1 = "56eb027d65b4d2dce6cb2e2d32c4d4afc9e1d707";
      };
    };
    "package-json-2.4.0" = {
      name = "package-json";
      packageName = "package-json";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json/-/package-json-2.4.0.tgz";
        sha1 = "0d15bd67d1cbbddbb2ca222ff2edb86bcb31a8bb";
      };
    };
    "got-5.7.0" = {
      name = "got";
      packageName = "got";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-5.7.0.tgz";
        sha1 = "718879e60f824cc0f69721127b835379b056a3af";
      };
    };
    "registry-auth-token-3.1.0" = {
      name = "registry-auth-token";
      packageName = "registry-auth-token";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-auth-token/-/registry-auth-token-3.1.0.tgz";
        sha1 = "997c08256e0c7999837b90e944db39d8a790276b";
      };
    };
    "registry-url-3.1.0" = {
      name = "registry-url";
      packageName = "registry-url";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-url/-/registry-url-3.1.0.tgz";
        sha1 = "3d4ef870f73dde1d77f0cf9a381432444e174942";
      };
    };
    "create-error-class-3.0.2" = {
      name = "create-error-class";
      packageName = "create-error-class";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-error-class/-/create-error-class-3.0.2.tgz";
        sha1 = "06be7abef947a3f14a30fd610671d401bca8b7b6";
      };
    };
    "duplexer2-0.1.4" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.1.4.tgz";
        sha1 = "8b12dab878c0d69e3e7891051662a32fc6bddcc1";
      };
    };
    "is-redirect-1.0.0" = {
      name = "is-redirect";
      packageName = "is-redirect";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-redirect/-/is-redirect-1.0.0.tgz";
        sha1 = "1d03dded53bd8db0f30c26e4f95d36fc7c87dc24";
      };
    };
    "is-retry-allowed-1.1.0" = {
      name = "is-retry-allowed";
      packageName = "is-retry-allowed";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-retry-allowed/-/is-retry-allowed-1.1.0.tgz";
        sha1 = "11a060568b67339444033d0125a61a20d564fb34";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "lowercase-keys-1.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.0.tgz";
        sha1 = "4e3366b39e7f5457e35f1324bdf6f88d0bfc7306";
      };
    };
    "node-status-codes-1.0.0" = {
      name = "node-status-codes";
      packageName = "node-status-codes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-status-codes/-/node-status-codes-1.0.0.tgz";
        sha1 = "5ae5541d024645d32a58fcddc9ceecea7ae3ac2f";
      };
    };
    "read-all-stream-3.1.0" = {
      name = "read-all-stream";
      packageName = "read-all-stream";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-all-stream/-/read-all-stream-3.1.0.tgz";
        sha1 = "35c3e177f2078ef789ee4bfafa4373074eaef4fa";
      };
    };
    "readable-stream-2.1.5" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.1.5.tgz";
        sha1 = "66fa8b720e1438b364681f2ad1a63c618448c9d0";
      };
    };
    "timed-out-3.0.0" = {
      name = "timed-out";
      packageName = "timed-out";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/timed-out/-/timed-out-3.0.0.tgz";
        sha1 = "ff88de96030ce960eabd42487db61d3add229273";
      };
    };
    "unzip-response-1.0.2" = {
      name = "unzip-response";
      packageName = "unzip-response";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unzip-response/-/unzip-response-1.0.2.tgz";
        sha1 = "b984f0877fc0a89c2c773cc1ef7b5b232b5b06fe";
      };
    };
    "url-parse-lax-1.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-1.0.0.tgz";
        sha1 = "7af8f303645e9bd79a272e7a14ac68bc0609da73";
      };
    };
    "capture-stack-trace-1.0.0" = {
      name = "capture-stack-trace";
      packageName = "capture-stack-trace";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/capture-stack-trace/-/capture-stack-trace-1.0.0.tgz";
        sha1 = "4a6fa07399c26bba47f0b2496b4d0fb408c5550d";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "prepend-http-1.0.4" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz";
        sha1 = "d4f4562b0ce3696e41ac52d0e002e57a635dc6dc";
      };
    };
    "rc-1.1.6" = {
      name = "rc";
      packageName = "rc";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.1.6.tgz";
        sha1 = "43651b76b6ae53b5c802f1151fa3fc3b059969c9";
      };
    };
    "deep-extend-0.4.1" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.1.tgz";
        sha1 = "efe4113d08085f4e6f9687759810f807469e2253";
      };
    };
    "ini-1.3.4" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.4.tgz";
        sha1 = "0537cb79daf59b59a1a517dff706c86ec039162e";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha1 = "1e15fbcac97d3ee99bf2d73b4c656b082bbafb91";
      };
    };
  };
in
{
  base16-builder = nodeEnv.buildNodePackage {
    name = "base16-builder";
    packageName = "base16-builder";
    version = "1.3.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/base16-builder/-/base16-builder-1.3.0.tgz";
      sha1 = "320eafea9333a8ea2bc8e04bda8db2537c52d23f";
    };
    dependencies = [
      sources."chalk-1.1.3"
      sources."ejs-2.5.2"
      sources."fs-promise-0.3.1"
      sources."js-yaml-3.6.1"
      sources."limax-1.4.1"
      sources."meow-3.7.0"
      sources."open-0.0.5"
      sources."update-notifier-0.6.3"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.0.0"
      sources."any-promise-0.1.0"
      sources."argparse-1.0.9"
      sources."esprima-2.7.3"
      sources."sprintf-js-1.0.3"
      sources."hepburn-1.0.0"
      sources."pinyin-2.6.2"
      sources."speakingurl-10.0.0"
      sources."bulk-replace-0.0.1"
      sources."commander-1.1.1"
      sources."nodejieba-1.4.11"
      sources."keypress-0.1.0"
      sources."nan-2.3.5"
      sources."camelcase-keys-2.1.0"
      sources."decamelize-1.2.0"
      sources."loud-rejection-1.6.0"
      sources."map-obj-1.0.1"
      sources."minimist-1.2.0"
      sources."normalize-package-data-2.3.5"
      sources."object-assign-4.1.0"
      sources."read-pkg-up-1.0.1"
      sources."redent-1.0.0"
      sources."trim-newlines-1.0.0"
      sources."camelcase-2.1.1"
      sources."currently-unhandled-0.4.1"
      sources."signal-exit-3.0.1"
      sources."array-find-index-1.0.2"
      sources."hosted-git-info-2.1.5"
      sources."is-builtin-module-1.0.0"
      sources."semver-5.3.0"
      sources."validate-npm-package-license-3.0.1"
      sources."builtin-modules-1.1.1"
      sources."spdx-correct-1.0.2"
      sources."spdx-expression-parse-1.0.4"
      sources."spdx-license-ids-1.2.2"
      sources."find-up-1.1.2"
      sources."read-pkg-1.1.0"
      sources."path-exists-2.1.0"
      sources."pinkie-promise-2.0.1"
      sources."pinkie-2.0.4"
      sources."load-json-file-1.1.0"
      sources."path-type-1.1.0"
      sources."graceful-fs-4.1.9"
      sources."parse-json-2.2.0"
      sources."pify-2.3.0"
      sources."strip-bom-2.0.0"
      sources."error-ex-1.3.0"
      sources."is-arrayish-0.2.1"
      sources."is-utf8-0.2.1"
      sources."indent-string-2.1.0"
      sources."strip-indent-1.0.1"
      sources."repeating-2.0.1"
      sources."is-finite-1.0.2"
      sources."number-is-nan-1.0.1"
      sources."get-stdin-4.0.1"
      sources."boxen-0.3.1"
      sources."configstore-2.1.0"
      sources."is-npm-1.0.0"
      sources."latest-version-2.0.0"
      sources."semver-diff-2.1.0"
      sources."filled-array-1.1.0"
      sources."string-width-1.0.2"
      sources."widest-line-1.0.0"
      sources."code-point-at-1.0.1"
      sources."is-fullwidth-code-point-1.0.0"
      sources."dot-prop-3.0.0"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."os-tmpdir-1.0.2"
      sources."osenv-0.1.3"
      sources."uuid-2.0.3"
      sources."write-file-atomic-1.2.0"
      sources."xdg-basedir-2.0.0"
      sources."is-obj-1.0.1"
      sources."os-homedir-1.0.2"
      sources."imurmurhash-0.1.4"
      sources."slide-1.1.6"
      sources."package-json-2.4.0"
      sources."got-5.7.0"
      sources."registry-auth-token-3.1.0"
      sources."registry-url-3.1.0"
      sources."create-error-class-3.0.2"
      sources."duplexer2-0.1.4"
      sources."is-redirect-1.0.0"
      sources."is-retry-allowed-1.1.0"
      sources."is-stream-1.1.0"
      sources."lowercase-keys-1.0.0"
      sources."node-status-codes-1.0.0"
      sources."read-all-stream-3.1.0"
      sources."readable-stream-2.1.5"
      sources."timed-out-3.0.0"
      sources."unzip-response-1.0.2"
      sources."url-parse-lax-1.0.0"
      sources."capture-stack-trace-1.0.0"
      sources."buffer-shims-1.0.0"
      sources."core-util-is-1.0.2"
      sources."inherits-2.0.3"
      sources."isarray-1.0.0"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-0.10.31"
      sources."util-deprecate-1.0.2"
      sources."prepend-http-1.0.4"
      sources."rc-1.1.6"
      sources."deep-extend-0.4.1"
      sources."ini-1.3.4"
      sources."strip-json-comments-1.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Base16 Builder is a nimble command-line tool that generates themes for your favourite programs.";
      homepage = "https://github.com/base16-builder/base16-builder#readme";
      license = "MIT";
    };
    production = true;
  };
}